---
- name: Install php-cli and php-fpm
  apt: name={{ item }} state=present
  with_items:
    - php5-cli
    - php5-fpm

- name: Copy over fpm/php.ini
  template: src=fpm_php.ini.j2 dest=/etc/php5/fpm/php.ini
            owner=root group=root mode=755
            force=yes backup=yes

- name: Copy over cli/php.ini
  template: src=cli_php.ini.j2 dest=/etc/php5/cli/php.ini
            owner=root group=root mode=755
            force=yes backup=yes