---
# Apache could be stealing the spotlight - some VPS images come with it
- name: Remove apache if it exists
  apt: name=apache* state=absent force=yes purge=yes

- name: Add the nginx repository signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add the nginx repository
  apt_repository: repo='deb http://nginx.org/packages/mainline/debian/ wheezy nginx' state=present

- name: Install nginx
  apt: name=nginx state=installed

- name: Copy across nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
        owner=root group=root mode=644
        force=yes backup=yes
  notify: restart nginx

# The nginx packages on the debian/ubuntu repositories create this directory,
# But the build sourced from nginx.org does not.
- name: Ensure the sites-available and sites-enabled directories exists
  file: path="/etc/nginx/{{ item }}" state=directory owner=root group=root mode=644
  with_items:
    - sites-available
    - sites-enabled

- name: Ensure a site includes directory exists
  file: path="{{ nginx_includes_path }}" state=directory owner=root group=root mode=644